#############################################################################
# Makefile for building: AnnFeatures
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  AnnFeatures.pro
# Template: app
# Command: /home/pajus/dev/Qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++ -I.
QMAKE         = /home/pajus/dev/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AnnFeatures1.0.0
DISTDIR = /home/pajus/Development/AnnFeatures/.tmp/AnnFeatures1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/pajus/dev/Qt/5.4/gcc_64
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		lib_ann/ann.cpp \
		lib_ann/classifier.cpp \
		lib_features/cornerfeatures.cpp \
		lib_features/edgefeatures.cpp \
		lib_features/experimentfeature.cpp \
		lib_features/facedescription.cpp \
		lib_features/featureextractor.cpp \
		lib_features/grayscalefeatures.cpp \
		lib_features/histogram.cpp \
		lib_features/histogramfeatures.cpp \
		lib_features/maskfeatures.cpp \
		lib_support/cvSupport.cpp \
		lib_support/support.cpp \
		lib_features/rawfeatures.cpp \
		lib_features/skeletfeatures.cpp \
		lib_features/hogfeatures.cpp \
		lib_features/blobfeatures.cpp \
		lib_features/lbpfeatures.cpp \
		lib_features/integralfeature.cpp \
		lib_features/brightfeature.cpp \
		lib_features/pointyfeature.cpp \
		lib_detector/detector.cpp \
		lib_stasm/stasm_lib.cpp \
		lib_stasm/stasm.cpp \
		lib_stasm/startshape.cpp \
		lib_stasm/shapemod.cpp \
		lib_stasm/shapehacks.cpp \
		lib_stasm/shape17.cpp \
		lib_stasm/print.cpp \
		lib_stasm/pinstart.cpp \
		lib_stasm/misc.cpp \
		lib_stasm/landmarks.cpp \
		lib_stasm/hatdesc.cpp \
		lib_stasm/hat.cpp \
		lib_stasm/faceroi.cpp \
		lib_stasm/eyedist.cpp \
		lib_stasm/eyedet.cpp \
		lib_stasm/err.cpp \
		lib_stasm/convshape.cpp \
		lib_stasm/classicdesc.cpp \
		lib_stasm/asm.cpp \
		lib_stasm/MOD_1/facedet.cpp \
		lib_stasm/MOD_1/initasm.cpp 
OBJECTS       = main.o \
		ann.o \
		classifier.o \
		cornerfeatures.o \
		edgefeatures.o \
		experimentfeature.o \
		facedescription.o \
		featureextractor.o \
		grayscalefeatures.o \
		histogram.o \
		histogramfeatures.o \
		maskfeatures.o \
		cvSupport.o \
		support.o \
		rawfeatures.o \
		skeletfeatures.o \
		hogfeatures.o \
		blobfeatures.o \
		lbpfeatures.o \
		integralfeature.o \
		brightfeature.o \
		pointyfeature.o \
		detector.o \
		stasm_lib.o \
		stasm.o \
		startshape.o \
		shapemod.o \
		shapehacks.o \
		shape17.o \
		print.o \
		pinstart.o \
		misc.o \
		landmarks.o \
		hatdesc.o \
		hat.o \
		faceroi.o \
		eyedist.o \
		eyedet.o \
		err.o \
		convshape.o \
		classicdesc.o \
		asm.o \
		facedet.o \
		initasm.o
DIST          = ../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/c++11.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		AnnFeatures.pro lib_ann/ann.h \
		lib_ann/classifier.h \
		lib_features/cornerfeatures.h \
		lib_features/edgefeatures.h \
		lib_features/experimentfeature.h \
		lib_features/facedescription.h \
		lib_features/featureextractor.h \
		lib_features/grayscalefeatures.h \
		lib_features/histogram.h \
		lib_features/histogramfeatures.h \
		lib_features/maskfeatures.h \
		lib_features/mouthwidthfeature.h \
		lib_support/cvSupport.h \
		lib_support/support.h \
		lib_features/rawfeatures.h \
		lib_features/skeletfeatures.h \
		lib_features/hogfeatures.h \
		lib_features/blobfeatures.h \
		lib_features/lbpfeatures.h \
		lib_features/integralfeature.h \
		lib_features/brightfeature.h \
		lib_features/pointyfeature.h \
		lib_detector/detector.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/startshape.h \
		lib_stasm/shapemod.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shape17.h \
		lib_stasm/print.h \
		lib_stasm/pinstart.h \
		lib_stasm/misc.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/landmarks.h \
		lib_stasm/hatdesc.h \
		lib_stasm/hat.h \
		lib_stasm/faceroi.h \
		lib_stasm/eyedist.h \
		lib_stasm/eyedet.h \
		lib_stasm/err.h \
		lib_stasm/convshape.h \
		lib_stasm/classicdesc.h \
		lib_stasm/basedesc.h \
		lib_stasm/atface.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/MOD_1/facedet.h main.cpp \
		lib_ann/ann.cpp \
		lib_ann/classifier.cpp \
		lib_features/cornerfeatures.cpp \
		lib_features/edgefeatures.cpp \
		lib_features/experimentfeature.cpp \
		lib_features/facedescription.cpp \
		lib_features/featureextractor.cpp \
		lib_features/grayscalefeatures.cpp \
		lib_features/histogram.cpp \
		lib_features/histogramfeatures.cpp \
		lib_features/maskfeatures.cpp \
		lib_support/cvSupport.cpp \
		lib_support/support.cpp \
		lib_features/rawfeatures.cpp \
		lib_features/skeletfeatures.cpp \
		lib_features/hogfeatures.cpp \
		lib_features/blobfeatures.cpp \
		lib_features/lbpfeatures.cpp \
		lib_features/integralfeature.cpp \
		lib_features/brightfeature.cpp \
		lib_features/pointyfeature.cpp \
		lib_detector/detector.cpp \
		lib_stasm/stasm_lib.cpp \
		lib_stasm/stasm.cpp \
		lib_stasm/startshape.cpp \
		lib_stasm/shapemod.cpp \
		lib_stasm/shapehacks.cpp \
		lib_stasm/shape17.cpp \
		lib_stasm/print.cpp \
		lib_stasm/pinstart.cpp \
		lib_stasm/misc.cpp \
		lib_stasm/landmarks.cpp \
		lib_stasm/hatdesc.cpp \
		lib_stasm/hat.cpp \
		lib_stasm/faceroi.cpp \
		lib_stasm/eyedist.cpp \
		lib_stasm/eyedet.cpp \
		lib_stasm/err.cpp \
		lib_stasm/convshape.cpp \
		lib_stasm/classicdesc.cpp \
		lib_stasm/asm.cpp \
		lib_stasm/MOD_1/facedet.cpp \
		lib_stasm/MOD_1/initasm.cpp
QMAKE_TARGET  = AnnFeatures
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = AnnFeatures


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AnnFeatures.pro ../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/c++11.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		AnnFeatures.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro
../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/c++11.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf:
AnnFeatures.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp lib_support/support.h \
		lib_support/cvSupport.h \
		lib_features/histogramfeatures.h \
		lib_features/featureextractor.h \
		lib_features/histogram.h \
		lib_features/cornerfeatures.h \
		lib_features/edgefeatures.h \
		lib_features/experimentfeature.h \
		lib_features/rawfeatures.h \
		lib_features/skeletfeatures.h \
		lib_features/hogfeatures.h \
		lib_features/integralfeature.h \
		lib_features/maskfeatures.h \
		lib_features/brightfeature.h \
		lib_features/pointyfeature.h \
		lib_features/lbpfeatures.h \
		lib_detector/detector.h \
		lib_detector/facedescription.h \
		lib_ann/ann.h \
		lib_ann/classifier.h \
		lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ann.o: lib_ann/ann.cpp lib_ann/ann.h \
		lib_ann/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ann.o lib_ann/ann.cpp

classifier.o: lib_ann/classifier.cpp lib_ann/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classifier.o lib_ann/classifier.cpp

cornerfeatures.o: lib_features/cornerfeatures.cpp lib_features/cornerfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cornerfeatures.o lib_features/cornerfeatures.cpp

edgefeatures.o: lib_features/edgefeatures.cpp lib_features/edgefeatures.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edgefeatures.o lib_features/edgefeatures.cpp

experimentfeature.o: lib_features/experimentfeature.cpp lib_features/experimentfeature.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o experimentfeature.o lib_features/experimentfeature.cpp

facedescription.o: lib_features/facedescription.cpp lib_features/facedescription.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facedescription.o lib_features/facedescription.cpp

featureextractor.o: lib_features/featureextractor.cpp lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o featureextractor.o lib_features/featureextractor.cpp

grayscalefeatures.o: lib_features/grayscalefeatures.cpp lib_features/grayscalefeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grayscalefeatures.o lib_features/grayscalefeatures.cpp

histogram.o: lib_features/histogram.cpp lib_features/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram.o lib_features/histogram.cpp

histogramfeatures.o: lib_features/histogramfeatures.cpp lib_features/histogramfeatures.h \
		lib_features/featureextractor.h \
		lib_features/histogram.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogramfeatures.o lib_features/histogramfeatures.cpp

maskfeatures.o: lib_features/maskfeatures.cpp lib_features/maskfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maskfeatures.o lib_features/maskfeatures.cpp

cvSupport.o: lib_support/cvSupport.cpp lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvSupport.o lib_support/cvSupport.cpp

support.o: lib_support/support.cpp lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o support.o lib_support/support.cpp

rawfeatures.o: lib_features/rawfeatures.cpp lib_features/rawfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawfeatures.o lib_features/rawfeatures.cpp

skeletfeatures.o: lib_features/skeletfeatures.cpp lib_features/skeletfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skeletfeatures.o lib_features/skeletfeatures.cpp

hogfeatures.o: lib_features/hogfeatures.cpp lib_features/hogfeatures.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hogfeatures.o lib_features/hogfeatures.cpp

blobfeatures.o: lib_features/blobfeatures.cpp lib_features/blobfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blobfeatures.o lib_features/blobfeatures.cpp

lbpfeatures.o: lib_features/lbpfeatures.cpp lib_features/lbpfeatures.h \
		lib_features/featureextractor.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbpfeatures.o lib_features/lbpfeatures.cpp

integralfeature.o: lib_features/integralfeature.cpp lib_features/integralfeature.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integralfeature.o lib_features/integralfeature.cpp

brightfeature.o: lib_features/brightfeature.cpp lib_features/brightfeature.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h \
		lib_features/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brightfeature.o lib_features/brightfeature.cpp

pointyfeature.o: lib_features/pointyfeature.cpp lib_features/pointyfeature.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pointyfeature.o lib_features/pointyfeature.cpp

detector.o: lib_detector/detector.cpp lib_detector/detector.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detector.o lib_detector/detector.cpp

stasm_lib.o: lib_stasm/stasm_lib.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stasm_lib.o lib_stasm/stasm_lib.cpp

stasm.o: lib_stasm/stasm.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stasm.o lib_stasm/stasm.cpp

startshape.o: lib_stasm/startshape.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o startshape.o lib_stasm/startshape.cpp

shapemod.o: lib_stasm/shapemod.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shapemod.o lib_stasm/shapemod.cpp

shapehacks.o: lib_stasm/shapehacks.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shapehacks.o lib_stasm/shapehacks.cpp

shape17.o: lib_stasm/shape17.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shape17.o lib_stasm/shape17.cpp

print.o: lib_stasm/print.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o print.o lib_stasm/print.cpp

pinstart.o: lib_stasm/pinstart.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pinstart.o lib_stasm/pinstart.cpp

misc.o: lib_stasm/misc.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o misc.o lib_stasm/misc.cpp

landmarks.o: lib_stasm/landmarks.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o landmarks.o lib_stasm/landmarks.cpp

hatdesc.o: lib_stasm/hatdesc.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hatdesc.o lib_stasm/hatdesc.cpp

hat.o: lib_stasm/hat.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hat.o lib_stasm/hat.cpp

faceroi.o: lib_stasm/faceroi.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faceroi.o lib_stasm/faceroi.cpp

eyedist.o: lib_stasm/eyedist.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyedist.o lib_stasm/eyedist.cpp

eyedet.o: lib_stasm/eyedet.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyedet.o lib_stasm/eyedet.cpp

err.o: lib_stasm/err.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o err.o lib_stasm/err.cpp

convshape.o: lib_stasm/convshape.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o convshape.o lib_stasm/convshape.cpp

classicdesc.o: lib_stasm/classicdesc.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classicdesc.o lib_stasm/classicdesc.cpp

asm.o: lib_stasm/asm.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o asm.o lib_stasm/asm.cpp

facedet.o: lib_stasm/MOD_1/facedet.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facedet.o lib_stasm/MOD_1/facedet.cpp

initasm.o: lib_stasm/MOD_1/initasm.cpp lib_stasm/stasm.h \
		lib_stasm/misc.h \
		lib_stasm/print.h \
		lib_stasm/err.h \
		lib_stasm/stasm_landmarks.h \
		lib_stasm/stasm_lib.h \
		lib_stasm/stasm_lib_ext.h \
		lib_stasm/atface.h \
		lib_stasm/landmarks.h \
		lib_stasm/landtab_muct77.h \
		lib_stasm/basedesc.h \
		lib_stasm/classicdesc.h \
		lib_stasm/hat.h \
		lib_stasm/hatdesc.h \
		lib_stasm/shapehacks.h \
		lib_stasm/shapemod.h \
		lib_stasm/asm.h \
		lib_stasm/MOD_1/facedet.h \
		lib_stasm/MOD_1/initasm.h \
		lib_stasm/eyedet.h \
		lib_stasm/convshape.h \
		lib_stasm/eyedist.h \
		lib_stasm/faceroi.h \
		lib_stasm/pinstart.h \
		lib_stasm/shape17.h \
		lib_stasm/startshape.h \
		lib_stasm/MOD_1/mh/yaw00.mh \
		lib_stasm/MOD_1/mh/yaw00_shapemodel.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p00_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p01_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p02_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p03_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p04_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p05_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p06_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p07_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p08_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p09_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p10_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p11_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p12_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p13_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p14_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p15_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p16_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p17_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p18_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p19_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p20_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p21_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p22_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p23_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p24_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p25_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p26_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p27_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p28_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p29_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p30_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p31_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p32_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p33_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p34_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p35_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p36_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p37_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p38_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p39_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p40_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p41_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p42_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p43_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p44_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p45_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p46_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p47_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p48_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p49_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p50_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p51_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p52_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p53_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p54_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p55_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p56_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p57_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p58_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p59_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p60_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p61_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p62_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p63_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p64_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p65_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p66_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p67_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p68_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p69_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p70_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p71_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p72_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p73_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p74_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p75_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev0_p76_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p00_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p01_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p02_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p03_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p04_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p05_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p06_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p07_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p08_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p09_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p10_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p11_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p12_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p13_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p14_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p15_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p16_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p17_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p18_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p19_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p20_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p21_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p22_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p23_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p24_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p25_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p26_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p27_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p28_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p29_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p30_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p31_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p32_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p33_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p34_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p35_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p36_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p37_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p38_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p39_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p40_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p41_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p42_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p43_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p44_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p45_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p46_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p47_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p48_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p49_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p50_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p51_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p52_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p53_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p54_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p55_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p56_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p57_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p58_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p59_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p60_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p61_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p62_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p63_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p64_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p65_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p66_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p67_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p68_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p69_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p70_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p71_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p72_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p73_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p74_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p75_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev1_p76_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p00_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p01_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p02_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p03_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p04_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p05_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p06_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p07_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p08_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p09_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p10_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p11_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p12_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p13_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p14_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p15_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p16_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p17_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p18_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p19_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p20_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p21_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p22_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p23_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p24_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p25_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p26_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p27_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p28_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p29_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p30_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p31_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p32_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p33_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p34_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p35_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p36_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p37_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p38_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p39_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p40_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p41_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p42_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p43_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p44_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p45_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p46_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p47_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p48_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p49_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p50_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p51_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p52_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p53_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p54_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p55_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p56_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p57_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p58_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p59_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p60_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p61_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p62_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p63_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p64_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p65_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p66_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p67_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p68_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p69_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p70_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p71_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p72_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p73_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p74_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p75_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev2_p76_hat.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p00_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p01_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p02_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p03_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p04_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p05_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p06_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p07_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p08_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p09_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p10_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p11_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p12_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p13_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p14_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p15_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p16_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p17_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p18_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p19_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p20_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p21_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p22_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p23_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p24_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p25_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p26_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p27_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p28_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p29_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p30_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p31_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p32_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p33_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p34_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p35_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p36_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p37_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p38_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p39_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p40_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p41_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p42_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p43_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p44_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p45_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p46_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p47_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p48_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p49_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p50_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p51_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p52_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p53_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p54_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p55_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p56_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p57_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p58_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p59_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p60_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p61_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p62_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p63_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p64_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p65_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p66_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p67_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p68_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p69_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p70_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p71_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p72_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p73_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p74_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p75_classic.mh \
		lib_stasm/MOD_1/mh/yaw00_lev3_p76_classic.mh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o initasm.o lib_stasm/MOD_1/initasm.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/AnnFeatures/bin || mkdir -p $(INSTALL_ROOT)/opt/AnnFeatures/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/AnnFeatures/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/AnnFeatures/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/AnnFeatures/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

