#############################################################################
# Makefile for building: AnnFeatures
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  AnnFeatures.pro
# Template: app
# Command: /home/pajus/dev/Qt/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++ -I.
QMAKE         = /home/pajus/dev/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AnnFeatures1.0.0
DISTDIR = /home/pajus/Development/AnnFeatures/.tmp/AnnFeatures1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/pajus/dev/Qt/5.4/gcc_64
LIBS          = $(SUBLIBS) -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		lib_features/cornerfeatures.cpp \
		lib_features/edgefeatures.cpp \
		lib_features/experimentfeature.cpp \
		lib_features/facedescription.cpp \
		lib_features/featureextractor.cpp \
		lib_features/grayscalefeatures.cpp \
		lib_features/histogram.cpp \
		lib_features/histogramfeatures.cpp \
		lib_features/maskfeatures.cpp \
		lib_support/cvSupport.cpp \
		lib_support/support.cpp \
		lib_features/rawfeatures.cpp \
		lib_features/skeletfeatures.cpp \
		lib_features/hogfeatures.cpp \
		lib_features/lbpfeatures.cpp \
		lib_classifiers/ann.cpp \
		lib_classifiers/classifier.cpp \
		lib_classifiers/svm.cpp \
		lib_classifiers/boostclass.cpp \
		lib_classifiers/kn.cpp 
OBJECTS       = main.o \
		cornerfeatures.o \
		edgefeatures.o \
		experimentfeature.o \
		facedescription.o \
		featureextractor.o \
		grayscalefeatures.o \
		histogram.o \
		histogramfeatures.o \
		maskfeatures.o \
		cvSupport.o \
		support.o \
		rawfeatures.o \
		skeletfeatures.o \
		hogfeatures.o \
		lbpfeatures.o \
		ann.o \
		classifier.o \
		svm.o \
		boostclass.o \
		kn.o
DIST          = ../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		AnnFeatures.pro lib_features/cornerfeatures.h \
		lib_features/edgefeatures.h \
		lib_features/experimentfeature.h \
		lib_features/facedescription.h \
		lib_features/featureextractor.h \
		lib_features/grayscalefeatures.h \
		lib_features/histogram.h \
		lib_features/histogramfeatures.h \
		lib_features/maskfeatures.h \
		lib_features/mouthwidthfeature.h \
		lib_support/cvSupport.h \
		lib_support/support.h \
		lib_features/rawfeatures.h \
		lib_features/skeletfeatures.h \
		lib_features/hogfeatures.h \
		lib_features/lbpfeatures.h \
		lib_classifiers/ann.h \
		lib_classifiers/classifier.h \
		lib_classifiers/svm.h \
		lib_classifiers/boostclass.h \
		lib_classifiers/kn.h main.cpp \
		lib_features/cornerfeatures.cpp \
		lib_features/edgefeatures.cpp \
		lib_features/experimentfeature.cpp \
		lib_features/facedescription.cpp \
		lib_features/featureextractor.cpp \
		lib_features/grayscalefeatures.cpp \
		lib_features/histogram.cpp \
		lib_features/histogramfeatures.cpp \
		lib_features/maskfeatures.cpp \
		lib_support/cvSupport.cpp \
		lib_support/support.cpp \
		lib_features/rawfeatures.cpp \
		lib_features/skeletfeatures.cpp \
		lib_features/hogfeatures.cpp \
		lib_features/lbpfeatures.cpp \
		lib_classifiers/ann.cpp \
		lib_classifiers/classifier.cpp \
		lib_classifiers/svm.cpp \
		lib_classifiers/boostclass.cpp \
		lib_classifiers/kn.cpp
QMAKE_TARGET  = AnnFeatures
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = AnnFeatures


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AnnFeatures.pro ../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		AnnFeatures.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro
../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/linux.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/qconfig.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
../../dev/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/default_post.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/yacc.prf:
../../dev/Qt/5.4/gcc_64/mkspecs/features/lex.prf:
AnnFeatures.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile AnnFeatures.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp lib_support/support.h \
		lib_support/cvSupport.h \
		lib_features/histogramfeatures.h \
		lib_features/featureextractor.h \
		lib_features/histogram.h \
		lib_features/cornerfeatures.h \
		lib_features/edgefeatures.h \
		lib_features/experimentfeature.h \
		lib_features/rawfeatures.h \
		lib_features/skeletfeatures.h \
		lib_features/hogfeatures.h \
		lib_features/lbpfeatures.h \
		lib_classifiers/svm.h \
		lib_classifiers/classifier.h \
		lib_classifiers/ann.h \
		lib_classifiers/boostclass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cornerfeatures.o: lib_features/cornerfeatures.cpp lib_features/cornerfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cornerfeatures.o lib_features/cornerfeatures.cpp

edgefeatures.o: lib_features/edgefeatures.cpp lib_features/edgefeatures.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edgefeatures.o lib_features/edgefeatures.cpp

experimentfeature.o: lib_features/experimentfeature.cpp lib_features/experimentfeature.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o experimentfeature.o lib_features/experimentfeature.cpp

facedescription.o: lib_features/facedescription.cpp lib_features/facedescription.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o facedescription.o lib_features/facedescription.cpp

featureextractor.o: lib_features/featureextractor.cpp lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o featureextractor.o lib_features/featureextractor.cpp

grayscalefeatures.o: lib_features/grayscalefeatures.cpp lib_features/grayscalefeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grayscalefeatures.o lib_features/grayscalefeatures.cpp

histogram.o: lib_features/histogram.cpp lib_features/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram.o lib_features/histogram.cpp

histogramfeatures.o: lib_features/histogramfeatures.cpp lib_features/histogramfeatures.h \
		lib_features/featureextractor.h \
		lib_features/histogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogramfeatures.o lib_features/histogramfeatures.cpp

maskfeatures.o: lib_features/maskfeatures.cpp lib_features/maskfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maskfeatures.o lib_features/maskfeatures.cpp

cvSupport.o: lib_support/cvSupport.cpp lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvSupport.o lib_support/cvSupport.cpp

support.o: lib_support/support.cpp lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o support.o lib_support/support.cpp

rawfeatures.o: lib_features/rawfeatures.cpp lib_features/rawfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawfeatures.o lib_features/rawfeatures.cpp

skeletfeatures.o: lib_features/skeletfeatures.cpp lib_features/skeletfeatures.h \
		lib_features/featureextractor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o skeletfeatures.o lib_features/skeletfeatures.cpp

hogfeatures.o: lib_features/hogfeatures.cpp lib_features/hogfeatures.h \
		lib_features/featureextractor.h \
		lib_support/cvSupport.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hogfeatures.o lib_features/hogfeatures.cpp

lbpfeatures.o: lib_features/lbpfeatures.cpp lib_features/lbpfeatures.h \
		lib_features/featureextractor.h \
		lib_support/support.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lbpfeatures.o lib_features/lbpfeatures.cpp

ann.o: lib_classifiers/ann.cpp lib_classifiers/ann.h \
		lib_classifiers/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ann.o lib_classifiers/ann.cpp

classifier.o: lib_classifiers/classifier.cpp lib_classifiers/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classifier.o lib_classifiers/classifier.cpp

svm.o: lib_classifiers/svm.cpp lib_classifiers/svm.h \
		lib_classifiers/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svm.o lib_classifiers/svm.cpp

boostclass.o: lib_classifiers/boostclass.cpp lib_classifiers/boostclass.h \
		lib_classifiers/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boostclass.o lib_classifiers/boostclass.cpp

kn.o: lib_classifiers/kn.cpp lib_classifiers/kn.h \
		lib_classifiers/classifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kn.o lib_classifiers/kn.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/AnnFeatures/bin || mkdir -p $(INSTALL_ROOT)/opt/AnnFeatures/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/AnnFeatures/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/AnnFeatures/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/AnnFeatures/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

